import { z } from "zod";
import { type FieldMeta } from "./fields";

function baseSchema(meta: FieldMeta): z.ZodTypeAny {
  switch (meta.kind) {
    case "text":
      return meta.required ? z.string().trim().min(1, "Required") : z.string().trim();
    case "email":
      return z.string().trim().email("Invalid email address");
    case "number":
      return z.coerce.number({ invalid_type_error: "Expected a number" });
    case "boolean":
      return z.boolean();
    case "date":
      return z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Expected a date in YYYY-MM-DD format");
    case "uuid":
    case "lookup":
      return z.string().uuid("Expected a valid id");
  }
}

/**
 * Zod schema for a single field. Optional fields accept `null`/`undefined`
 * and normalize empty strings (typical for HTML form inputs) to `null`.
 */
export function fieldSchema(meta: FieldMeta): z.ZodTypeAny {
  const base = baseSchema(meta);
  if (meta.required) {
    return meta.kind === "boolean" ? z.boolean().default(false) : base;
  }
  return z
    .preprocess((value) => (value === "" || value === undefined ? null : value), base.nullable())
    .optional();
}

export function buildInsertSchema(
  fields: Record<string, FieldMeta>,
  primaryKey: string,
): z.ZodTypeAny {
  const shape: z.ZodRawShape = {};
  for (const [key, meta] of Object.entries(fields)) {
    // The primary key is generated by the database but may be supplied
    // explicitly (e.g. when seeding data).
    shape[key] = key === primaryKey ? z.string().uuid().optional() : fieldSchema(meta);
  }
  return z.object(shape);
}

export function buildUpdateSchema(
  fields: Record<string, FieldMeta>,
  primaryKey: string,
): z.ZodTypeAny {
  const shape: z.ZodRawShape = {};
  for (const [key, meta] of Object.entries(fields)) {
    if (key === primaryKey) continue;
    // Required fields stay non-nullable but become optional: a PATCH may
    // omit them, it just cannot null them out.
    shape[key] = meta.required ? fieldSchema(meta).optional() : fieldSchema(meta);
  }
  return z.object(shape);
}
