import { CodeBlock } from "@/components/CodeBlock";

export default function EntitiesPage() {
  return (
    <>
      <h1>Entities &amp; fields</h1>
      <p>
        An entity is a named record of fields. <code>entity()</code> turns chainable field builders
        into plain, serializable metadata plus generated Zod schemas.
      </p>

      <h2>Field kinds</h2>
      <table>
        <thead>
          <tr>
            <th>Builder</th>
            <th>TypeScript type</th>
            <th>PostgreSQL column</th>
            <th>Form input</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <code>field.text()</code>
            </td>
            <td>string</td>
            <td>text</td>
            <td>text input</td>
          </tr>
          <tr>
            <td>
              <code>field.email()</code>
            </td>
            <td>string</td>
            <td>text</td>
            <td>email input</td>
          </tr>
          <tr>
            <td>
              <code>field.number()</code>
            </td>
            <td>number</td>
            <td>double precision</td>
            <td>number input</td>
          </tr>
          <tr>
            <td>
              <code>field.boolean()</code>
            </td>
            <td>boolean</td>
            <td>boolean</td>
            <td>checkbox</td>
          </tr>
          <tr>
            <td>
              <code>field.date()</code>
            </td>
            <td>string (YYYY-MM-DD)</td>
            <td>date</td>
            <td>date input</td>
          </tr>
          <tr>
            <td>
              <code>field.uuid()</code>
            </td>
            <td>string</td>
            <td>uuid</td>
            <td>text input</td>
          </tr>
          <tr>
            <td>
              <code>field.lookup(Entity, &#123; label &#125;)</code>
            </td>
            <td>string (foreign key)</td>
            <td>uuid</td>
            <td>select</td>
          </tr>
        </tbody>
      </table>

      <h2>Modifiers</h2>
      <CodeBlock>{`field.text()
  .required()          // non-nullable + validated
  .label("Full name")  // overrides the auto-generated label

field.uuid().primary() // exactly one per entity; generated by the database`}</CodeBlock>
      <p>
        Labels are auto-generated when omitted: <code>unitPrice</code> becomes “Unit Price”, and
        lookup fields drop their <code>Id</code> suffix, so <code>countryId</code> becomes
        “Country”.
      </p>

      <h2>Lookups</h2>
      <CodeBlock>{`countryId: field.lookup(Country, { label: "name" })`}</CodeBlock>
      <p>
        A lookup stores the referenced entity&apos;s primary key. Grids resolve it to the label
        field, and forms render a select with options loaded from the generated API. The
        <code> label</code> key is type-checked against the target entity&apos;s fields.
      </p>

      <h2>Validation</h2>
      <p>
        Every entity carries an <code>insertSchema</code> and an <code>updateSchema</code> (partial,
        primary key excluded). The same schemas run in the form before submitting and in the server
        handler — one source of truth, validated twice.
      </p>

      <h2>Row types</h2>
      <CodeBlock>{`import { type InferRow } from "@datacanvas/core";

type CustomerRow = InferRow<typeof Customer>;
// { id: string; name: string; email: string | null; countryId: string | null }`}</CodeBlock>
    </>
  );
}
